import sys

# --- Global Variables & Constants ---
input_string = "(sum + 47) / total"  # Example input to parse
input_pos = 0                        # Current position in input_string
nextChar = ''                        # The current character
charClass = 0                        # The class of the current char
lexeme = ""                          # The string being built
nextToken = 0                        # The code for the token found

# Character Classes
LETTER = 0
DIGIT = 1
UNKNOWN = 99
EOF = -1

# Token Codes
INT_LIT = 10
IDENT = 11
ASSIGN_OP = 20
ADD_OP = 21
SUB_OP = 22
MULT_OP = 23
DIV_OP = 24
LEFT_PAREN = 25
RIGHT_PAREN = 26
EOF_TOKEN = 99

# --- Lexical Analyzer Functions ---

def getChar():
    """Gets the next character from input and determines its class"""
    global input_pos, nextChar, charClass
    
    if input_pos < len(input_string):
        nextChar = input_string[input_pos]
        input_pos += 1
        
        if nextChar.isalpha():
            charClass = LETTER
        elif nextChar.isdigit():
            charClass = DIGIT
        else:
            charClass = UNKNOWN
    else:
        charClass = EOF
        nextChar = ""

def addChar():
    """Adds the current character to the lexeme string"""
    global lexeme
    lexeme += nextChar

def lookup(char):
    """Returns the token code for single-character operators"""
    if char == '(': return LEFT_PAREN
    if char == ')': return RIGHT_PAREN
    if char == '+': return ADD_OP
    if char == '-': return SUB_OP
    if char == '*': return MULT_OP
    if char == '/': return DIV_OP
    return EOF_TOKEN

def lex():
    """The main scanner function. Skips whitespace and finds the next token."""
    global lexeme, charClass, nextToken
    lexeme = ""
    
    # Skip whitespace
    while charClass == UNKNOWN and nextChar.isspace():
        getChar()
    
    # Case 1: Parse Identifiers (Variables like 'sum')
    if charClass == LETTER:
        addChar()
        getChar()
        while charClass == LETTER or charClass == DIGIT:
            addChar()
            getChar()
        nextToken = IDENT

    # Case 2: Parse Integer Literals (Numbers like '47')
    elif charClass == DIGIT:
        addChar()
        getChar()
        while charClass == DIGIT:
            addChar()
            getChar()
        nextToken = INT_LIT

    # Case 3: Parse Parentheses and Operators
    elif charClass == UNKNOWN:
        nextToken = lookup(nextChar)
        addChar()
        getChar()

    # Case 4: End of File
    elif charClass == EOF:
        nextToken = EOF_TOKEN
        lexeme = "EOF"
    
    print(f"Next token is: {nextToken}, Next lexeme is: {lexeme}")
    return nextToken

# --- Syntax Analyzer Functions ---

def expr():
    """Parses strings in the language generated by the rule: <expr> -> <term> {(+ | -) <term>}"""
    # print("Enter <expr>")
    
    term() # Parse the first Term
    
    while nextToken == ADD_OP or nextToken == SUB_OP:
        lex()
        term()
    
    # print("Exit <expr>")

def term():
    """Parses strings generated by the rule: <term> -> <factor> {(* | /) <factor>}"""
    # print("Enter <term>")
    
    factor() # Parse the first Factor
    
    while nextToken == MULT_OP or nextToken == DIV_OP:
        lex()
        factor()
        
    # print("Exit <term>")

def factor():
    """Parses strings generated by the rule: <factor> -> id | int_constant | ( <expr> )"""
    # print("Enter <factor>")
    
    if nextToken == IDENT or nextToken == INT_LIT:
        lex() # Get the next token
        
    elif nextToken == LEFT_PAREN:
        lex() # Consume '('
        expr() # Recursively call expr
        
        if nextToken == RIGHT_PAREN:
            lex() # Consume ')'
        else:
            print("ERROR: Missing right parenthesis")
            
    else:
        print("ERROR: Syntax error")
        
    # print("Exit <factor>")

# --- Main Execution ---
if __name__ == "__main__":
    print(f"Parsing Input: {input_string}\n")
    
    # Initialize
    getChar() # Get first char
    lex()     # Get first token
    
    # Start parsing
    expr()
    
    print("\nParsing complete.")